version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: redis
    versions:
    - 0.19.0
  - dependency-name: gotham_derive
    versions:
    - 0.5.0
  - dependency-name: gotham
    versions:
    - 0.5.0
  - dependency-name: r2d2_redis
    versions:
    - 0.13.0
  - dependency-name: hyper
    versions:
    - 0.12.35
